### ISSUE TITLE
Suppression du champ Horodatage Requête ?

### ISSUE THREAD

**Issue by aminvielledebat** [before-interop/emutation#10]
Ne pourrait-on pas proposer la suppression du champ « Horodatage Requête » dans la réponse. Je peux comprendre dans la requête, mais moins dans la réponse.

Dans le cas contraire, que faire si l'OI renvoie une valeur différente de celle de l'OC ?

**Comment by jlsaxione** [comment]
en accord.

**Comment by aminvielledebat** [comment]
Je ferme, on rouvrira au besoin pour une prochaine version.
