### ISSUE TITLE
Utilisation des SoapFault plutôt que des codes de retour sur erreur

### ISSUE THREAD

**Issue by aminvielledebat** [before-interop/emutation#11]
Il est question, dans la spécification, de codes de retour à mettre en place dans toutes les réponses.
Cela impliquera donc un code HTTP 200, qui correspond à un OK, mais qui sera en réalité un KO.
En termes de maintenance, et de code, c’est une catastrophe.

Avec notre rôle de conseiller technique, ne pourrait-on pas proposer l’utilisation des SoapFault pour porter ces erreurs ?
Elles porteraient les codes, et les libellés définis dans la spécification, et on donc resterait iso-fonctionnel (mais pas iso solution technique proposée bien entendu).

Dans la pratique, nous aurions donc un code http 500, et un message/code spécifique pour la gestion de toutes les erreurs.
Ainsi, on verrait du premier coup d’œil si le service a répondu un OK, ou un KO (via le code http), et l’analyse du KO pourrait être simplifié avec une catégorisation des Faults (i.e telle ou telle opération peut renvoyer telle ou telle Fault).

Pour le développeur OC, le cas de gestion serait alors très simple : pour le cas nominal, il n’y a rien à vérifier, la mutation est faite, et le service rendu.
Pour tous les autres cas, on peut décider de ce qu’il est bon de faire, ou pas, à la demande côté OC.
Grosso modo cela donne quelque chose comme : 
![image](https://user-images.githubusercontent.com/37697258/37857513-ba4fc51c-2efb-11e8-81e0-4eb5633ff0c1.png)

**Comment by jlsaxione** [comment]
Bonjour, 
peut on le faire ? ou est il trop tard pour changer cette feature ?

**Comment by aminvielledebat** [comment]
Perso, je peux faire une PR. Reste à savoir si elle sera regardée et validée ;-)

Idem il faudrait un coup de revue sur les autres sujets en cours (notamment la PR d'altitude qu'il faudrait merger ou découper en deux pour bien identifier les différents changes).

**Comment by olaissac-bt** [comment]
Est-ce vraiment nécessaire de changer cela maintenant ? Gérer les erreurs fonctionnelles en tant qu'Exception me semble plus compliqué tout de même. Et pour en avoir parler à nos développeurs, je n'ai pas eu de retour particulièrement positif sur les SOAPFault.

**Comment by aminvielledebat** [comment]
Hello @olaissac-bt.

D'un point de vue fonctionnel, cela ne change rien, on reste iso spec, et cela a au moins le mérite de normaliser quelles erreurs peuvent être utilisées par quelles opérations, et avec quelle code.

D'un point de vue technique, cela fait partie des best practices du soap. Ce n'est pas une position Orange, mais bien une position du dev sur Soap en général. Tu trouveras pas mal d'articles sur le sujet chez Microsoft ou IBM qui expliquent bien que cette technique est celle à adopter quand on fait des appels synchrones non batchés (ce qui est notre cas).

Si on continue sur la technique, je peux insister sur ce que j'ai dit dans mon mail à savoir : 
- L'utilisation des faults te permet de mettre en place une supervision du webservice au niveau http, et donc d'avoir une vision très rapidement du bon usage du service
- L'utilisation des soap faults simplifie le travail du développeur dans le sens où il n'a pas à se poser de questions "est ce que la réponse est OK ou pas" (ce qui est déjà pas mal :smile:).

Enfin, pour ce qui est de la charge induite pour les développeurs avec l'utilisation des faults, il n'y a pas plus de travail étant donné que le code des clients est généré à partir du wsdl.
Le seul changement est de passer de ce code : 

```php
$client = new MonClientEmutation('monfichier.wsdl');
$reponse = $client->MiseAJourRouteOptique($mesParametres);
if ($reponse->getCodeRetour()->getCodeRetour() === 0 and $reponse->getCodeRetour()->getCodeErreur() != "Les codes qui sont des erreurs ?") {
   $monServiceQuiTraiteMaReponse->requeteOKCas1($reponse);
} elseif($reponse->getCodeRetour()->getCodeRetour() === 0 and  $reponse->getCodeRetour()->getCodeErreur() = "Le Code d'erreur qui n'est pas une erreur bloquante") {
   $monServiceQuiTraiteMaReponse->requeteOKCas2($reponse);
} elseif ($reponse->getCodeRetour()->getCodeRetour() === 1 and$reponse->getCodeRetour()->getCodeErreur() === "Quel Code ?") {
   $monServiceQuiTraiteMaReponse->requeteKOCas1($reponse);
} elseif ($reponse->getCodeRetour()->getCodeRetour() === 1 and$reponse->getCodeRetour()->getCodeErreur() === "Quel Code 2?") {
   $monServiceQuiTraiteMaReponse->requeteKOCas2($reponse);
} 
// etc
```

à (si on veut faire très simple) :

```php
try {
  $client = new MonClientEmutation('monfichier.wsdl');
  $reponse = $client->MiseAJourRouteOptique($mesParametres);
  // ici la réponse est toujours OK
  $monServiceQuiTraiteMaReponse->requeteOK($reponse);
  // maintenant on gère les KO avec une gestion par défaut
} catch (\Exception $e) {
  $monServiceQuiTraiteMaReponse->requeteKOParDefaut($reponse);
}
```

ou à (si on veut faire un peu plus compliqué) : 

```php
try {
  $client = new MonClientEmutation('monfichier.wsdl');
  $reponse = $client->MiseAJourRouteOptique($mesParametres);
  // ici la réponse est toujours OK
  $monServiceQuiTraiteMaReponse->requeteOK($reponse);
  // maintenant on ne gère que les KO, parce que l'on a décidé de le faire
} catch (TechnicalFault $e) {
  $monServiceQuiTraiteMaReponse->requeteKoTechnique($reponse);
} catch (FunctionalFault $e) {
  $monServiceQuiTraiteMaReponse->requeteKoFonctionnel($reponse);
} catch (\Exception $e) {
  $monServiceQuiTraiteMaReponse->requeteKOParDefaut($reponse);
}
```

Pour le dev, c'est quand même plus simple :smile:.
La vraie question à se poser quand on parle des soapfaults, c'est : 
> est ce que le développeur veut/sait travailler avec des exceptions (car les soapfaults sont mappées sur des exceptions) ou pas ?

J'espère que c'est le cas :smile:.

**Comment by olaissac-bt** [comment]
Chaque équipe de développement peut avoir ses préférences. La simplicité dépend des outils que chacun utilise et des normes internes. Cela dit, si vous y tenez on s'adaptera. Pas de veto de notre part.
