### ISSUE TITLE
code java généré par cxf

### ISSUE THREAD

**Issue by jlsaxione** [before-interop/emutation#15]
Etes vous intéressé par un exemple de projet maven pour générer le client depuis le wsld ? 
Si oui voulez vous que je push un exemple sur le repo ?

**Comment by aminvielledebat** [comment]
Yes !

Je suis en train de push la PR pour le travis.yml pour du php.
On fait une PR globale avec ma branche sur ce repo et tu complètes pour java ?

**Comment by jlsaxione** [comment]
Go

**Comment by jlsaxione** [comment]
je peux donner un exemple aussi pour le golang

**Comment by aminvielledebat** [comment]
Fait pour la PR, même si deux trois trucs encore à boucler.

Et vas y pour Go, c'est toujours :-)

**Comment by jlsaxione** [comment]
tout est prêt
je crée une pull request ? 
Je créerai une pull request pour chaque techno.

**Comment by aminvielledebat** [comment]
Yes, je pense que c'est le mieux. Après à voir si on préfère : 
-  faire N PRs sur la PR en WIP que j'ai faite, et on merge le tout dans le master quand on a un premier package de langages pas déconnant.
- On valide/merge ma première PR, puis on en fait N sur le master (notre gestion d'historique aimera bien mieux :-))

**Comment by jlsaxione** [comment]
les branches sont crées et je m'occupe de faire les pulls requests

**Comment by jlsaxione** [comment]
on peut fermer cette issue ?

**Comment by aminvielledebat** [comment]
Done
