### ISSUE TITLE
Caractère optionnel d'un noeud et de sa valeur

### ISSUE THREAD

**Issue by aminvielledebat** [before-interop/emutation#6]
Toutes les types de base ont été surchargés pour ajouter la propriété ```nillable```. On aura donc toujours des balises dans le corps de nos messages, mais pas forcément avec du contenu dedans (mais l’attribut ```xsi :nil=true```)

De mon côté, je suis plus pour une approche « pas de donnée, pas de nœud », mais là encore, ça se discute.
Si on combine ça avec le ```minOccurs```,  comment gère-t-on le cas d’un type ```nillable``` avec un ```minOccurs = 0``` ?
Je sais que le sujet est souvent soumis à interprétation, et même si il reste la spécification interop’ pour avoir le dernier mot, un schéma restrictif est toujours meilleur.

**Comment by jlsaxione** [comment]
Il faut faire aussi attention sur comment son fait les clients.
Sinon pour moi, je pars du même principe.

**Comment by jlsaxione** [comment]
On fait du SOAP il faut rester le plus restrictif possible.
