### ISSUE TITLE
Suppression du champ identifiantReponse et création du champ identiantRequete ?

### ISSUE THREAD

**Issue by aminvielledebat** [before-interop/emutation#9]
On nous demande de gérer le champ « identifiantReponse », mais techniquement, je ne vois pas le cas d’application. Une idée ?
Par contre, je pense qu’il serait intéressant d’avoir un « uuid » pour identifier la requête et mettre en place la traçabilité OI/OC.

**Comment by jlsaxione** [comment]
Même principe que la soapfault, le UUID est plus approprié.
